# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - scaled_joint_trajectory_controller_D
    - scaled_joint_trajectory_controller_I

  scaled_joint_trajectory_controller_D:
    type: FollowJointTrajectory
    joints:
      - ur_dual_D_shoulder_pan_joint
      - ur_dual_D_shoulder_lift_joint
      - ur_dual_D_elbow_joint
      - ur_dual_D_wrist_1_joint
      - ur_dual_D_wrist_2_joint
      - ur_dual_D_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true
  scaled_joint_trajectory_controller_I:
    type: FollowJointTrajectory
    joints:
      - ur_dual_I_shoulder_pan_joint
      - ur_dual_I_shoulder_lift_joint
      - ur_dual_I_elbow_joint
      - ur_dual_I_wrist_1_joint
      - ur_dual_I_wrist_2_joint
      - ur_dual_I_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true