controller_manager:

  ros__parameters:
    "2FG7_outwards_controller":
      joint_state_controller:
        type: "joint_state_controller/JointStateController"
        publish_rate: 50
      lef_finger_joint_position_controller:
        type: "effort_controllers/JointPositionController"
        joint: "lef_finger_joint"
        pid: {p: 100.0, i: 0.01, d: 10.0}
